### PR TITLE
[SAGE-295] foundations toast update

### PR DESCRIPTION
**Pull request by QuintonJason**
## Description

- [x] align toast components to foundations spec

Implementation note: Implementation ticket to resolve: [SAGE-426](https://kajabi.atlassian.net/browse/SAGE-426)
The following files have references to `Sage.toast.trigger` and will need their `icon` updated to `check-circle-filled` and `danger-filled` respectively
```
app/assets/javascripts/admin/flash_messages.js
app/assets/javascripts/admin/marketing_email_templates.js
app/assets/javascripts/admin/offer_edit_details.js
app/assets/javascripts/admin/offer_upsell_modal.js
app/assets/javascripts/admin/offers_form.js
app/assets/javascripts/admin/save_as_template_campaign.js
app/assets/javascripts/admin/save_as_template.js
app/assets/javascripts/admin/settings/custom_domain.js
```

## Screenshots

|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-03-29 at 6 42 47 PM|Screen Shot 2022-03-29 at 6 27 56 PM|

## Testing in `sage-lib`

- In Rails, visit the [Toast view](http://localhost:4000/pages/component/toast)
- Interact with any of the Toasts and verify updated styles
**Currently React story does not exist**

## Testing in `kajabi-products`

1. (**LOW**) Minor visual styles and icon update for the Toast component.

## Related

Closes [SAGE-295](https://kajabi.atlassian.net/browse/SAGE-295)

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
LGTM! 👍🏼  - Would you mind creating a follow-up issue in the backlog, just so we don't forget to update these icons when the time comes?

**Review by anechol — CHANGES_REQUESTED** [review]
Nice update! A couple things:
- Can we make the font weight `600`? It's listed as Medium in the Figma file but medium for us means Semibold because of the weird weight names for this font.
- The hover state for the remove icon makes it unreadable

General question:
- Is there an underlying reason we chose to apply a height on the element instead of padding?

**Comment by QuintonJason** [comment]
> Nice update! A couple things:
> 
> * Can we make the font weight `600`? It's listed as Medium in the Figma file but medium for us means Semibold because of the weird weight names for this font.
> * The hover state for the remove icon makes it unreadable
> 
> General question:
> 
> * Is there an underlying reason we chose to apply a height on the element instead of padding?

The initial reason was that the toast would switch out content and without the height it would collapse.

**Review by anechol — APPROVED** [review]
The height reasoning totally makes sense, thanks! LGTM 🚀

**Pull request merged**
