### PR TITLE
fix(copy-button): use new clipboard functions

### PR DESCRIPTION
**Pull request by ju-Skinner**
we still have a fallback to use execCommand for legacy browser support

JIRA Ticket: [DSS-388](https://kajabi.atlassian.net/browse/DSS-388)

## Description
It was discovered that the `copy-button` was not working in certain browsers (versions). The code implemented here addresses both current versions and legacy version support which falls back to using `execCommand('copy')`.

## Testing in `sage-lib`
1. Navigate to the Copy Button component on the documentation site. 
2. In each browser, Chrome (v111 and v112), Safari, and Firefox confirm that the functionality behaves as expected. 

## Testing in `kajabi-products`
1. (**HIGH**) Copy button is broken in Chrome version 112 or higher. Please check with all major browsers
   - [ ] Navigate [here](https://www.kajabi.test/admin/settings/account ), under Account Details, scroll to API Credentials under and confirm the copy-button
   - [ ] Navigate [here](https://app.kajabi.com/admin/settings/security) and click "Set up authenticator". Once you enter your password, you should see a copy button under the QR code. Confirm that it functions as expected. 

[DSS-388]: https://kajabi.atlassian.net/browse/DSS-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by pixelflips — COMMENTED** [review]
Seems to be working properly in Blink/Chromium browsers, but getting an error message in the toast for Webkit(Safari) and Gecko(FF).


Chrome 111 - Works
Chrome Beta 113 - Works
Chrome Canary 114 - Works
Edge 112 - Works
Firefox 112 - Error Message
Safari 16.4 - Error Message
Safari Tech Preview 168 - Error Message

Screenshot 2023-04-26 at 1 45 33 PM

**Comment by ju-Skinner** [comment]
> Seems to be working properly in Blink/Chromium browsers, but getting an error message in the toast for Webkit(Safari) and Gecko(FF).
> 
> Chrome 111 - Works Chrome Beta 113 - Works Chrome Canary 114 - Works Edge 112 - Works Firefox 112 - Error Message Safari 16.4 - Error Message Safari Tech Preview 168 - Error Message
> 
> Screenshot 2023-04-26 at 1 45 33 PM

@pixelflips Can you provide a bit more details about the Safari browser you tested with, please? I tested with my local version of Safari (16.4.1) and it works as expected. See the [loom](https://www.loom.com/share/03203b1406554b21bbfc26aec7cd7b6c) video for reference. 

I will download Firefox and see what's going on there.

**Review by pixelflips — APPROVED** [review]
🔥 Rechecked all the same browsers as before and all is working as expected now. Great work!

**Review by monkeypox8 — APPROVED** [review]
👍 LGTM

Not related to this work: as a follow-up we may want the examples to differ in their text. Having the same repeated string makes it tricky to tell which button you've used.

**Pull request merged**
