### PR TITLE
Button: React documentation updates

### PR DESCRIPTION
**Pull request by monicawheeler**
## Description

Update the React documentation to more clearly outline the options available to `<Button>`

## Screenshots from button
|  Before  |  After  |
|--------|--------|
| Screen Shot 2023-08-23 at 2 56 31 PM |Screen Shot 2023-08-23 at 2 57 21 PM|
| Screen Shot 2023-08-23 at 2 56 45 PM | Screen Shot 2023-08-23 at 2 57 28 PM |

## Screenshots from toolbar editor
|  Before  |  After  |
|--------|--------|
| Screen Shot 2023-08-23 at 2 57 14 PM | Screen Shot 2023-08-23 at 3 13 24 PM |

## Testing in `sage-lib`
1. Navigate to [button](http://localhost:4100/?path=/docs/sage-button--primary) 
2. Verify the Button documentation is fully representative of the button component
3. Navigate to [toolbar editor](http://localhost:4100/?path=/docs/sage-toolbareditor--default)
4. Verify the toolbar editor documentation for the buttons is accurate

## Testing in `kajabi-products`
1. (**LOW**) No props were altered, documentation changes only

### CODE REVIEW

**Review by ju-Skinner — APPROVED** [review]
LGTM...The only concern I had was how the source code was rendered. The indentation was off. I couldn't find a simple way to fix it. 

image

**Review by pixelflips — APPROVED** [review]
🔥🔥🔥

**Comment by monicawheeler** [comment]
> LGTM...The only concern I had was how the source code was rendered. The indentation was off. I couldn't find a simple way to fix it.
> image

I absolutely agree and battled with this for a bit. I haven't given up and will continue to explore correcting it.

**Comment by monicawheeler** [comment]
FYI @ju-Skinner and @pixelflips - I removed the redundant "children" as a prop from two button examples and made a minor formatting adjustment. This does not change the output of the PR.

**Pull request merged**
