### PR TITLE
Next version bump (~v3.24.0)

### PR DESCRIPTION
**Pull request by philschanely**
1. #457 #462 #463  (BREAKING) Type spec setup is updated with minimal visible adjustments; general inspection of `kajabi-products` pages that use Sage should show no negative side effects. [This PR](https://github.com/Kajabi/kajabi-products/pull/18868) will merge in a few necessary patches.
1. #456 (BREAKING) This unifies status colors into a token. There is no change to the app since the strings within the property don't change. PR to patch references: https://github.com/Kajabi/kajabi-products/pull/18886
1. #428 (MEDIUM) Reduce size of the tiny-mce editor buttons. Also allows the buttons to wrap to multiple lines.
    - [ ] Coaching session edit form
    - [ ] Podcast episode edit form
    - [ ] Product post page
    - [ ] Offer edit form
1. #438 (MEDIUM) This will be a visible change to all modal content color 
    - [ ] Import Podcast modal
    - [ ] Distribution View Steps modal
    - [ ] New Podcast Episode modal
1. #447 #464 (MEDIUM) This affects every <textarea> field in the app, but should only affect a visual change that field has a value
    - [ ] New Offers Modal
    - [ ] Coaching Program Edit Details Modal
1. #440 (LOW) This affect every instance of a scrollable table existing panel.
    - [ ] Podcast Index
    - [ ] People index
1. #455 (LOW) Fixes a bug with panel controls' current display item count. 
    - [ ] Verify that pagination displays correct value for all pages in a result set on People page.
1. #439  (LOW) Documentation updates. No impact on existing components.
1. #448 (LOW) This adds a new property to components and has no effect on existing usage within the app
1. #429 (LOW) Added unit testing framework for Sage React. No impact; development tool only
1. #453 (MEDIUM) Added the ability to add a background color to the Rails Icon Component.
1. #454 (LOW) Modal: adds new events on "open" for JS listeners. Not expected to affect current usage, but the following checks are recommended to make ensure functionality is working as expected.
   - [ ] Offers -> New offer (Offer setup modal, requires `comm_offer_setup_modal_ui` feature flag   
   - [ ] Products: New Product modal
   - [ ] Newsletters: Add Newsletter modal
   - [ ] Website -> Navigation: New Navigation Menu modal
1. #433 (LOW) Removes dropdown, adds an optional link to name and related_property, and adds new transaction_state text for Transaction Card. This component is not currently in use and these changes are being made in preparation for work to begin during the next cycle.

### CODE REVIEW

**Comment by QuintonJason** [comment]
Currently investigating an issue with the input's label not animating above the input, hiding part of that input's value. Not sure if new or not
Screen_Shot_2021-05-05_at_10_13_40_AM

**Comment by philschanely** [comment]
> Currently investigating an issue with the input's label not animating above the input, hiding part of that input's value. Not sure if new or not
> Screen_Shot_2021-05-05_at_10_13_40_AM

FIxed by #463

**Comment by QuintonJason** [comment]
I have to resolve an issue with hover state of the textarea

**Review by QuintonJason — APPROVED** [review]
👍  nice!

**Review by pixelflips — APPROVED** [review]
LGTM! 👍🏼

**Review by monkeypox8 — APPROVED** [review]
👍🏼  LGTM!

**Pull request merged**
