### PR TITLE
Update Pagination

### LINKED ISSUE #514: Update Pagination
## Description

Update component to match latest specs in Sage 3.0. The following were noted during initial audit:

- Sync up interactive states
- Double-check border-radius colors and type specs

**Dependencies**:
- [Interactive states](https://github.com/Kajabi/sage-lib/issues/491)
- [Border radius](https://github.com/Kajabi/sage-lib/issues/472)

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=3561%3A9796)
- [Existing component(s)](https://sage-design-system.kajabi.com/pages/component/pagination)

### PR DESCRIPTION
**Pull request by pixelflips**
## Description
Updates pagination colors, radius, and interactions in order to bring up to design spec.
Fixes #514

## Screenshots

|  Before  |  After  |
|--------|--------|
|Screen Shot 2021-07-30 at 2 16 54 PM|Screen Shot 2021-07-30 at 2 16 44 PM|

## Testing in `sage-lib`
Visit http://localhost:4000/pages/component/pagination
Verify styling updates and interactions align with [Figma design](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=6999%3A22277)

## Testing in `kajabi-products`
1. (**LOW**) Updates styling of pagination to meet design spec. No impact is expected.
   - [ ] Quick sanity check of pagination should be done. Payments & People.

## Related
#514

### CODE REVIEW

**Review by joedakroub — COMMENTED** [review]
All looks good except I am seeing the following issue on focus:

Pagination - Focus

**Review by joedakroub — APPROVED** [review]
@pixelflips and I synced on what seemed to be a focus issue, but it looks like `focus-visible` is causing this, but this is also happening in `master` so it can wait for a future PR. Nice work Phillip! 👍🏼

**Comment by pixelflips** [comment]
> @pixelflips and I synced on what seemed to be a focus issue, but it looks like `focus-visible` is causing this, but this is also happening in `master` so it can wait for a future PR. Nice work Phillip! 👍🏼

@joedakroub I was able to work it out so feel free to have a quick look if interested. Thanks for the troubleshooting help too btw!!

**Comment by joedakroub** [comment]
@pixelflips This looks great in every browser! Nice work Phillip! 🙌🏼 🏆

**Review by QuintonJason — APPROVED** [review]

**Pull request merged**
