### PR TITLE
Form input: add optional 'name' param

### PR DESCRIPTION
**Pull request by monkeypox8**
## Description
Minor update allowing `SageFormInput` and `SageFormTextarea` to accept custom `name` values. This attribute is present on checkboxes, radios, etc. but was somehow overlooked for text inputs. This is needed in cases where an input `name` must match an existing field/table.  When left blank, the `name` attribute will duplicate the `id` for its output.

- Various documentation cleanup items
- Removed legacy `markup.html.erb` file

### Estimated impact

- (**LOW**) Adds optional `name` parameter to SageFormInput. Not expected to affect existing components. Check the following examples to ensure expected behavior:
  - [x] Landing page slug field (Website -> Pages -> Edit Details): `/app/views/admin/template_metadata/_form_fields.html.erb`
- (**LOW**) Adds optional `name` parameter to SageFormTextarea. Not currently in use within app.

## Related
n/a

### CODE REVIEW

**Review by joedakroub — APPROVED** [review]
Nice addition Kevin! Thanks for updating this and the docs. 👍🏼

**Review by philschanely — APPROVED** [review]
Helpful improvement and good catches on the docs too! 🙌

**Review by pixelflips — APPROVED** [review]
👍🏼  LGTM! Nice work!

**Review by QuintonJason — APPROVED** [review]
💥  nice touch

**Pull request merged**
