### PR TITLE
SAGE-734 - Doc site search

### LINKED ISSUE #760: [BUG] Container component does not load in Sage Docs
## Detailed description

Accessing the [Container](https://sage-design-system.kajabi.com/pages/component/container) component in the Sage Docs, does not load and throws an error. Local and in production

## Steps to reproduce

1. Navigate to [Container](https://sage-design-system.kajabi.com/pages/component/container)
2. Observe the error

## Screenshots

Screen Shot 2021-09-01 at 10 10 39 AM

### PR DESCRIPTION
**Pull request by cmcfadzean**
## Description

Adds simple search to the doc site; searches component names.

### Search button in header
Screen Shot 2022-01-07 at 2 28 12 PM

### Search page
Screen Shot 2022-01-07 at 2 28 35 PM

### Search results
Screen Shot 2022-01-07 at 2 28 56 PM

## Testing in `sage-lib`
- [ ] Check to see that the search returns the components you would expect. 

## Testing in `kajabi-products`
1. (**N/A**) This is a Sage change only. No testing on `kajabi-products`.

### CODE REVIEW

**Review by monicawheeler — APPROVED** [review]
Looks great!

**Comment by anechol** [comment]
Oh, hey I didn't know you were working on the Container page. I just [merged in a fix](https://github.com/Kajabi/sage-lib/pull/764) for that, but if removing the link makes more sense, then that's cool!

**Review by pixelflips — APPROVED** [review]
LGTM! One small thing is that the search isn't available on the homepage which would be awesome since that's the page I usually navigate to first. Would save a click if I could hop right to the search from there as well. Definitely not a show-stopper.

**Comment by pixelflips** [comment]
> LGTM! One small thing is that the search isn't available on the homepage...

Doh! Just noticed it is on the homepage, just not in the header where I first went looking. Again not a show-stopper.

**Comment by monicawheeler** [comment]
@pixelflips - I agree that we should have a home navbar search option but adding one is not a simple plug-and-go. I am going to leave the search just within the site, not on the home page navigation for now. Thank you for the review!

**Pull request merged**
