### PR TITLE
fix(storybook): add the Toast story back

### PR DESCRIPTION
**Pull request by ju-Skinner**
## Jira Ticket
https://kajabi.atlassian.net/browse/DSS-201

## Description
Adds the `Toast` story back. 

## EDIT
Fixed the SVG path with @monkeypox8 suggestion. Thanks

### CODE REVIEW

**Review by pixelflips — COMMENTED** [review]
@ju-Skinner This is working fantastic on the `Canvas` tab, but the `Docs` tab always displays the same toast when I'm switching from default to the link variant from in the sidebar.

That may be expected and not a major blocker. Let me know either way I'm happy to give the 👍🏼

**Comment by ju-Skinner** [comment]
> @ju-Skinner This is working fantastic on the `Canvas` tab, but the `Docs` tab always displays the same toast when I'm switching from default to the link variant from in the sidebar.
> 
> 
> 
> That may be expected and not a major blocker. Let me know either way I'm happy to give the 👍🏼 

It should have both stories, one at the top "default" and another below the properties "with link". This would be similar to Drop-down. I'll take a look in the morning.

**Review by pixelflips — APPROVED** [review]
🔥 Looks and works great, nice work!

**Review by monkeypox8 — APPROVED** [review]
👍🏼 LGTM

Note for follow-up: loading variant icons are animating strangely. SVG path seems to be missing the standalone `.sage-loader__spinner-path` class in the React component.

<details>
<summary>loading toast</summary>

</details>

**Review by QuintonJason — APPROVED** [review]
Looks and works great

**Comment by ju-Skinner** [comment]
@monkeypox8 fixed in [this](https://github.com/Kajabi/sage-lib/pull/1643/commits/c9134485770a829070d97e6a0fea683ed10d93ae) commit

**Review by pixelflips — APPROVED** [review]

**Review by monkeypox8 — APPROVED** [review]
:shipit:

**Pull request merged**
