### PR TITLE
[DSS-344] Search Design Audit Updates

### PR DESCRIPTION
**Pull request by pixelflips**
## Description
Updates search component styling based on design audit.

 - Updated the border styling on the default input.
 - Updated the `:hover` state styling on the default input.

## Screenshots

||  Before  |  After  |
|--------|--------|--------|
|`default`|Screenshot 2023-03-16 at 10 44 09 AM|Screenshot 2023-03-16 at 10 43 53 AM|
|`:hover`|Screenshot 2023-03-16 at 10 44 53 AM|Screenshot 2023-03-16 at 10 51 36 AM|

## Testing in `sage-lib`

**Rails/Docs**

- Navigate to [Search](http://localhost:4000/pages/component/search?tab=preview) 
- Verify the default border matches the [design spec](https://www.figma.com/file/sMbtLUHSt2vfKgKjyQ3052/%F0%9F%A7%A9-Sage-components?node-id=3516%3A22970&t=OyPYvh75Z9HovGaA-1)
- Verify the default `:hover` matches the design spec

**React/Storybook**

- Navigate to [Search](http://localhost:4100/?path=/story/sage-search--default) 
- Verify the default border matches the [design spec](https://www.figma.com/file/sMbtLUHSt2vfKgKjyQ3052/%F0%9F%A7%A9-Sage-components?node-id=3516%3A22970&t=OyPYvh75Z9HovGaA-1)
- Verify the default `:hover `matches the design spec

## Testing in `kajabi-products`
1. (**LOW**) Updates border and hover styling of the default Search component. Styling only updates.

## Related
DSS-344

### CODE REVIEW

**Review by goodwinchris — APPROVED** [review]

**Comment by goodwinchris** [comment]
I am seeing some super minor visual inconsistencies with the designs, looks like the border sits one pixel further from the text than expected and the magnifying glass icon is a little smaller than expected.

**Comment by pixelflips** [comment]
> I am seeing some super minor visual inconsistencies with the designs, looks like the border sits one pixel further from the text than expected and the magnifying glass icon is a little smaller than expected.

@goodwinchris I'll check w/ design as the original ticket does not mention any changes to those.

**Comment by pixelflips** [comment]
> I am seeing some super minor visual inconsistencies with the designs, looks like the border sits one pixel further from the text than expected and the magnifying glass icon is a little smaller than expected.

@goodwinchris good eye on those 🦅 . I've adjusted and I think those should be correct now as well. Have another quick look when you have a minute and thanks for catching those as I only focused on the exact line items in the ticket.

**Review by QuintonJason — APPROVED** [review]
Looks great!

**Review by goodwinchris — APPROVED** [review]
Love it, thanks for humoring me!

**Pull request merged**
