### PR TITLE
[CHORE] - upgrade node v16.20

### PR DESCRIPTION
**Pull request by ju-Skinner**
## Description
Upgrade to Node v16.

### CODE REVIEW

**Review by KZeillmann — APPROVED** [review]
Looks like Node 16 to me :shipit:

**Review by voodooGQ — APPROVED** [review]

**Review by rwc9u — APPROVED** [review]
🤘 🚢

**Comment by rwc9u** [comment]
https://github.com/Kajabi/sage-lib/actions/runs/5603412429/jobs/10249992415?pr=1766#step:5:8

**Review by QuintonJason — APPROVED** [review]
Tested on `16.20.0` locally. Clicked through all top level pages and spot checked component pages and subsequent tabs on those component pages

**Pull request merged**
