### PR TITLE
[SAGE-11] Foundations: Update border tokens

### PR DESCRIPTION
**Pull request by QuintonJason**
## Description

- [x] update `border-radius` values 
- [x] change `border-radius` values in the following components:
    - Alert
    - Hero
    - Modal
    - Stat box
    - Upload Card

##### Card
|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-01-28 at 1 53 26 PM|Screen Shot 2022-01-28 at 1 51 52 PM|

##### Panel
|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-01-28 at 10 46 28 AM|Screen Shot 2022-01-28 at 10 42 20 AM|

##### Alert
|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-01-28 at 1 41 44 PM|Screen Shot 2022-01-28 at 1 40 53 PM|

##### Modal
|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-01-28 at 10 47 52 AM|Screen Shot 2022-01-28 at 10 47 13 AM|

##### Stat box
|  Before  |  After  |
|--------|--------|
|||

##### Upload Card
|  Before  |  After  |
|--------|--------|
|Screen Shot 2022-01-28 at 1 31 33 PM|Screen Shot 2022-01-28 at 1 36 52 PM|

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

Closes [SAGE-11](https://kajabi.atlassian.net/browse/SAGE-11)

### CODE REVIEW

**Review by philschanely — APPROVED** [review]
Wow amazing what difference this makes in the system feeling different already! 🙌

**Comment by philschanely** [comment]
@QuintonJason this should also be pointed to the epic branch, right?

**Review by monicawheeler — APPROVED** [review]
💯

**Review by monkeypox8 — CHANGES_REQUESTED** [review]
Looks like `border-radius` on SagePanelFigure isn't carrying across as expected:



Setting `border-radius: inherit` on `.sage-panel__figure--bleed-top` seems to fix it. Token change is looking great everywhere else.

**Comment by QuintonJason** [comment]
> Looks like `border-radius` on SagePanelFigure isn't carrying across as expected:
> 
> sage-panel-figure
> 
> Setting `border-radius: inherit` on `.sage-panel__figure--bleed-top` seems to fix it. Token change is looking great everywhere else.

Nice find! 🔬  I'll get this updated in the am as the bridge

**Comment by QuintonJason** [comment]
Screen Shot 2022-02-01 at 8 45 23 AM
@monkeypox8 pushed a fixed. Thanks again for the sharp eye

**Review by monkeypox8 — APPROVED** [review]
👍 LGTM, nice work!

**Pull request merged**
