### PR TITLE
Next version bump

### PR DESCRIPTION
**Pull request by QuintonJason**
Changes included ranked by impact on existing work in Products:

### Impact

1. (Medium) Update Feature Toggle image render conditionally #281 
1. (Medium) Update Dropdown `items` to add selected option on pageload #284 
1. (Medium) Fix React textarea cursor jumping bug #290 
1. (Low) New Transaction Card #286
1. (Medium) Update form elements using Parsley to use sage form validation styles #294 
1. (Low) Panel row and stack updates in React #298 
1. (Medium) Panel and Card footer alignment #293 
1. (Low) Adds strikethrough styles to React type dictionary #302 
1. (Medium) Adds spacing and compositional improvements to React Modals #296 
1. (Medium) Adds LabelGroup and LabelSecondaryButton to assist composition in Labels #295 
1. (Medium) Adds modifier to react Dropdown to allow external labels for selected items #295 
1. (Low) Add fullWidth modifier to React Button #295 
1. (Low) Correct validation `border-color` issue #304 
1. (Low) Updated the image dimensions in the Feature Toggle component #305 
1. (Low) Update IconCard coloring #307 

### QA Testing Guidelines

- [ ] (1) This work should not affect existing implementations of Feature Toggle. Check existing Feature Toggles built with Rails to see that they function as expected. For example check:
	- [ ] Products Beta Features Page
- [ ] (2) This work should affect existing implementations of Dropdowns, most notably dropdowns that control views in tabular data. Check existing dropdowns after sorting a page. After the page refresh, the previously selected option's text should populate the dropdown trigger
- [ ] (3) This work affects `<Textarea>` react components. Ensure textareas successful pass their value up through to their parent via `onChange` prop and that there is not state value state management happening within that component.
- [ ] (4) N/A -- new component
- [ ] (5) This work affects all `<input>`s, `<textarea>`s, and `<select>`s. When visiting any form page within the app, click the `Save` button while all the fields are blank. Verify that the error states reflect sage styles and not parsley styles
- [ ] (6) Existing implementations of React-based Panel.Row and Panel.Stack should be unaffected. Verify the following display as expected:
    - [ ] Product outline manager - action bar at top under search has expected layout
    - [ ] People > Filters dropdown - rows have expected layout
 - [ ] (7) Affects all areas of content using `.sage-card__footer` or `.sage-panel__footer` (mobile only)
 - [ ] (8) No affect on existing features.
 - [ ] (9) React-based Modals should not be impacted but now have features that make them easier to compose headers and to space the body of the modal. Verify existing React-based Modals behave as expected:
    - [ ] New Contact Imports > Mapping step (map columns modals)
    - [ ] Product outline editor (any modals)
- [ ] (10) Label: ensure labels look same and function as they have to date:
    - [ ] Product outline editor (React): publish status dropdowns
    - [ ] Contact import bulk actions step (React): Tag selections that appear below dropdown
    - [ ] Settings > Domain (Rails): see `Kajabi default` is displaying as before
    - [ ] Offers (Rails): publish status label appears as expected (FYI: clicking off of this dropdown does not appear to function as expected and dismiss the dropdown. This appears to be the functionality before this PR as well. A patch may be needed to how this component is implemented here.)
- [ ] (11) Dropdown:
    - [ ] Product outline editor (React): any existing dropdowns
    - [ ] Contact import bulk actions step (React): Tag selection dropdown
    - [ ] Offers (Rails): ... options menu
    - [ ] Product catalogue (Rails): any dropdowns
- [ ] (12) Button: no changes should affect React-based buttons. Confirm that any buttons in the follow appear as expected:
  - [ ] New Contact import process
  - [ ] Product outline manager
- [ ] (13) Affects form elements that contain valid values after they return an error after validation
  - [ ] Go to the Products page -> Go the Podcasts page in the sidebar -> Click on New Podcast -> here's that page for a shortcut: http://www.kajabi.test:3000/admin/sites/1/podcasts/new -> Click Save, then you'll see validation errors -> In the Title field, add some text and the error state will be removed -> Click on the Hosted By field -> Verify that the Title field's default color is the sage border gray
- [ ] (14) This work will affect existing implementations of Feature Toggle. Check existing Feature Toggles built with Rails to see that they function as expected. For example check:
	- [ ] Products Beta Features Page
- [ ] (15) Component is not currently in use in the app but is needed for upcoming work.

### CODE REVIEW

**Review by philschanely — APPROVED** [review]
Check as much as I was familiar with and a few others with Bridge. Parsley-related work and the new selected feature in dropdown were not as familiar to me.

**Review by pixelflips — APPROVED** [review]
👍🏼  LGTM! Great work everyone!

**Review by monkeypox8 — APPROVED** [review]
👍🏼 LGTM, did a quick test bridging Sell/Commerce, looking great!

**Comment by QuintonJason** [comment]
Found one minor issue. Added a follow up PR: https://github.com/Kajabi/sage-lib/pull/304

**Review by joedakroub — APPROVED** [review]
Checked labels/dropdowns in Offers, Coupons, modals in the products outline view and the Beta Labs feature toggle. All looking good! 👍🏼

**Pull request merged**
