### PR TITLE
[DSS-342] Icons: Update icon font (v.15, 2 new)

### PR DESCRIPTION
**Pull request by pixelflips**
## Description
Adds 2 new icons to Sage:

## Screenshots

|  Name  |   |
|--------|--------|
|`ai-writer`|Screenshot 2023-02-22 at 3 44 21 PM|
|`ai-writer-filled`|Screenshot 2023-02-22 at 3 44 35 PM|

## Testing in `sage-lib`

**Docs Site:**

1. Navigate to [icons](http://localhost:4000/pages/foundations/icon)
2. Verify new icons are added to the system
3. Verify all icons are rendering as expected
4. Verify fonts are served from the `/v15` directory from CDN (Network panel in dev tools)

**Storybook:**

1. Navigate to [icons](http://localhost:4100/?path=/docs/sage-icon--default)
2. Verify new icons are added to the system
3. Verify all icons are rendering as expected

## Testing in `kajabi-products`
1. (**LOW**) Updated icon font w/ 2 new icons. No KP impact is expected.

## Related
DSS-342

### CODE REVIEW

**Comment by pixelflips** [comment]
> 👍 LGTM
> 
> @Kajabi/ux-devs Since the icon font update will have to remain manual for the time being, I'd suggest we clarify the process for everyone with a few steps. Continually incrementing the CDN for each update is starting to get messy.
> 
> 1. Make note in the shared design channel of a batch icon update (including a cutoff date)
> 2. Leave the icon update PR unmerged until the next bump to catch any stragglers
> 3. Keep the latest 1-2 versions on the CDN, and remove anything older (if permissions allow, may need to check with PE)

**Comment by pixelflips** [comment]
@ monkeypox8 this is a great idea. @monicawheeler is this something you could help us with documenting and clarifying to the right teams?

**Comment by monicawheeler** [comment]
@pixelflips - happy to! Great callout @monkeypox8 🤝

**Comment by pixelflips** [comment]
@monkeypox8 & @monicawheeler - I am going to merge this one and we can share out the new process/info and kick it off with the next one. I just want to wrap this one up since my time will be limited to keep an eye on it.

**Pull request merged**
