### PR TITLE
[Sage-495] Sage 3 - Radio, Checkbox, and Switch

### LINKED ISSUE #495: Controls L1: Checkbox, Radio, Switch
## Description

Update component to match latest specs in Sage 3.0.

- Consider unifying as much as possible between these through mixin(s) or a common base/wrapper.
- Be sure to check places within system these components are used and prevent major issues, but leave spec matching for those components to their related tickets. (Notes on such other tickets would be welcomed!)

**Dependencies**:
- [Border radius](https://github.com/Kajabi/sage-lib/issues/472)
- [Interactive states](https://github.com/Kajabi/sage-lib/issues/491)

**Links**
- [Figma specs](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/WIP-Sage-3-%E2%80%94-Admin-Components?node-id=4244%3A16524)
- Existing component/s:
	- [Radio](https://sage-design-system.kajabi.com/pages/component/radio)
	- [Checkbox](https://sage-design-system.kajabi.com/pages/component/checkbox)
	- [Switch](https://sage-design-system.kajabi.com/pages/component/switch)

### PR DESCRIPTION
**Pull request by FuturaExtraBold**
## Description
1. Unifies the most common styles for form toggles Radio, Checkbox, and Switch via mixins. These changes are merely code refactor, not visual. 
2. Fixed styling concerns to match Figma specs. These changes are visual.
3. Changed hover states to `sage-color(primary, 400)`.
4. Changed focus outlines to `sage-color(primary, 400)`.
5. Removed space in between Switch focus outline and Switch element per Figma.
6. Tweaked Radio and Checkbox focus width and border-radii, per Figma.

## Screenshots

|  Before  |  After  |
|--------|--------|
|image|image|
|image|image|
|image|image|

### Rails
- View [Radio](http://localhost:4000/pages/component/radio)
- View [Checkbox](http://localhost:4000/pages/component/checkbox)
- View [Switch](http://localhost:4000/pages/component/switch)
- Check that toggles are sized properly and functioning as normal

### React
- View [Radio](http://localhost:4100/?path=/docs/sage-radio--default)
- View [Checkbox](http://localhost:4100/?path=/docs/sage-checkbox--default)
- View [Switch](http://localhost:4100/?path=/docs/sage-switch--default)
- Check that toggles are sized properly and functioning as normal

## Testing in `kajabi-products`
(**MEDIUM**) Changes the sizing and spacing for all Radios, Checkboxes, and Switches. Please sanity-test that all form toggle elements look nice and function normally.

## Related

Closes #495

### CODE REVIEW

**Review by anechol — COMMENTED** [review]
Hey nice work! The only thing I've noticed is that we don't have the `Blue 400` hover states for these. Can we add those in? I also see that the focus ring is different, but I'm assuming that's addressed in another ticket or has changed since this Figma design was created.

**Comment by FuturaExtraBold** [comment]
Good catch, @anechol! I will work on those now!

**Review by anechol — APPROVED** [review]
Awesome! LGTM 🚀

**Review by philschanely — APPROVED** [review]
Looking really good here! One small visual thing I noticed is in the bordered version of radio for the new version the bolded first line still has a greater left gap than the line below it. IMO the larger space looks better there but just thought it might need another look.

**Comment by philschanely** [comment]
@FuturaExtraBold BTW LOOOVE all the combining of same stuff through mixins. :trophy:

**Review by QuintonJason — APPROVED** [review]

**Pull request merged**
