### PR TITLE
Rails components - verify existence of html_attributes

### PR DESCRIPTION
**Pull request by QuintonJason**
## Description

Added `<%= component.generated_html_attributes.html_safe %>` to all remaining props to ensure that any rails props can be passed any html attributes needed
 - [x] - updated assistant
 - [x] - updated avatar
 - [x] - updated banner
 - [x] - updated billboard
 - [x] - updated body
 - [x] - updated breadcrumbs
 - [x] - updated buttongroup
 - [x] - updated catalog item
 - [x] - updated container
 - [x] - updated content
 - [x] - updated copybutton
 - [x] - updated copytext
 - [x] - updated copytextcard
 - [x] - updated datacard
 - [x] - updated description
 - [x] - updated dropdown
 - [x] - updated expandablecard
 - [x] - updated featuretoggle
 - [x] - updated forminput
 - [x] - updated formsection
 - [x] - updated formselect
 - [x] - updated formtextarea
 - [x] - updated gridcol
 - [x] - updated gridrow
 - [x] - updated header
 - [x] - updated hero
 - [x] - updated iconlist
 - [x] - updated indicator
 - [x] - updated inputgroup
 - [x] - updated inputhelper
 - [x] - updated labelgroup
 - [x] - updated loader
 - [x] - updated meter
 - [x] - updated modal
 - [x] - updated modalcontent
 - [x] - updated nav
 - [x] - updated nullview
 - [x] - updated overlay
 - [x] - updated pageheading
 - [x] - updated pagination
 - [x] - updated panel controls
 - [x] - update popover
 - [x] - updated search
 - [x] - updated sidebar
 - [x] - updated sortable
 - [x] - updated sortableitem
 - [x] - updated stage
 - [x] - updated statusicon
 - [x] - updated switch
 - [x] - updated tabspane
 - [x] - updated tooltip
 - [x] - updated transactioncard
 - [x] - updated uploadcard

### Screenshots

No visual changes

### Steps for testing
There is no visual change. This PR allow for adding `html_attributes` to any Rails component to add custom data-attributes and other properties.

The best way to test is to turn on the link and add a prop to any component -> inspect that element -> verify that the `html_attributes` have been added
    
### QA Steps
(Low) This updates existing Rails components but props are new features so there should be no difference.

### CODE REVIEW

**Review by joedakroub — COMMENTED** [review]
This is a terrific and much-needed addition to our components!

One thing I noticed in the sandbox example, it looks like the `SageLabel` attributes are getting rendered incorrectly. See the `data-dog` attribute example:

SageLabel

**Review by philschanely — APPROVED** [review]
After addressing @joedakroub comment this should def go in asap!

**Comment by philschanely** [comment]
@joedakroub what data structure did you provide that led to this errant output?

**Comment by joedakroub** [comment]
@philschanely This example that is provided in the Sandbox is the structure that is rendering improperly: `docs/app/views/pages/sandbox.html.erb`

**Comment by QuintonJason** [comment]
> This is a terrific and much-needed addition to our components!
> 
> One thing I noticed in the sandbox example, it looks like the `SageLabel` attributes are getting rendered incorrectly. See the `data-dog` attribute example:
> 
> SageLabel

Good catch! I've seen that before. On it.

**Review by joedakroub — APPROVED** [review]
Confirmed that the Sandbox example is now working properly. Thanks! 👍🏼

**Pull request merged**
