### PR TITLE
[SAGE-268] Color Token shim

### PR DESCRIPTION
**Pull request by monkeypox8**
## Description
[SAGE-268](https://kajabi.atlassian.net/browse/SAGE-268)

Temporarily adds `charcoal` color tokens for use with Sage bridge in `kajabi-products`. Sage documentation will **not** be updated, since `charcoal` will be deprecated.

Note that only values **100** through **500** have been converted in figma. The remainder are duplicates of `grey` values.

## Testing in `sage-lib`
Verify that the docs site works as expected

## Testing in `kajabi-products`
Run the Sage bridge to confirm that webpack is no longer throwing errors.

1. (**HIGH**) Adds temporary charcoal values to color tokens

### CODE REVIEW

**Comment by monkeypox8** [comment]
Corresponding issue to address once in-app patches are complete: https://kajabi.atlassian.net/browse/SAGE-271

**Review by pixelflips — APPROVED** [review]
LGTM! 👍🏼  Checked both docs and kp w/ bridge and did not see the errors anymore! Thanks for the quick turnaround. This will be super useful!

**Review by monicawheeler — APPROVED** [review]
🙌🏻

**Review by philschanely — APPROVED** [review]
Thanks for this, @monkeypox8 !!

**Pull request merged**
