### PR TITLE
feat(tab): update tab and tabs to align with Next designs

### PR DESCRIPTION
**Pull request by monicawheeler**
## Description

Update tab to align with new designs 

## Screenshots

|  Before  |  After  |
|--------|--------|
| Screen Shot 2022-04-22 at 1 00 22 PM | tabbing through tabs |

## Testing in `sage-lib`
1. Navigate to http://localhost:4000/pages/component/tabs
2. Confirm styles align with new designs

## Testing in `kajabi-products`
1. (**LOW**) Next - Tab updates to new designs. No affect on `kp`.

## Related
[SAGE-231](https://kajabi.atlassian.net/browse/SAGE-231)

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
Overall LGTM! 👍🏼

**Comment by monicawheeler** [comment]
@pixelflips - Thanks for the look! I am not sure where I have the 16px spacing, could you provide some more details on where you see that? I have `sage-tabs &:not(:last-child)` set to `margin-right: sage-spacing(md)` which is 24px. Happy to pair up as well! Thank you!

**Comment by pixelflips** [comment]
> @pixelflips - Thanks for the look! I am not sure where I have the 16px spacing, could you provide some more details on where you see that? I have `sage-tabs &:not(:last-child)` set to `margin-right: sage-spacing(md)` which is 24px. Happy to pair up as well! Thank you!

@monicawheeler Hmm... I am seeing `margin-right: sage-spacing(sm);` - let me make sure it's not a cache issue. Will reply back. Stay tuned.

**Comment by pixelflips** [comment]
@monicawheeler not exactly sure why, but ignore my comment. Spacing is fine after clearing cache and restarting my local env. Sorry for the confusion. All looks great!

**Pull request merged**
