### PR TITLE
Sage font update

### PR DESCRIPTION
**Pull request by joedakroub**
## Description
This PR updates the Sage font with the following icon:
- check-circle-filled

## Testing in `sage-lib`
1. Visit http://0.0.0.0:4000/pages/foundations/icon and ensure that the `check-circle-filled` icon appears and that all icons appear as they should

## Testing in `kajabi-products`
1. (**LOW**) This change adds a new icon so it is not in use in Kajabi Products, but the icon unicode mappings changed significantly this time, so testing is needed wherever icons appear:
   - [ ] Dashboard (sidenav)
   - [ ] Settings
   - [ ] Products
   - [ ] Website
   - [ ] Sales
   - [ ] Marketing
   - [ ] Analytics

### CODE REVIEW

**Review by monicawheeler — CHANGES_REQUESTED** [review]
Just an FYI - The Calendly font does not render properly. 
Screen Shot 2021-09-02 at 4 35 27 PM

I've been meaning to look into this: https://kajabi.slack.com/archives/C01A424HY8Y/p1630011028009200?thread_ts=1629842914.095200&cid=C01A424HY8Y

This is a PR I started for the icon:
https://github.com/Kajabi/sage-lib/pull/750

**Comment by joedakroub** [comment]
@monicawheeler I removed the `calendly` icon for the moment.

**Review by pixelflips — APPROVED** [review]
LGTM! 👍🏼

**Review by philschanely — APPROVED** [review]

**Comment by philschanely** [comment]
@joedakroub and @monicawheeler I suggest we handle this Calendly icon in `kp` as an SVG and some local styling. I don't see a strong case for it being part of Sage's icon library.

**Review by monkeypox8 — APPROVED** [review]
👍🏼 LGTM

**Pull request merged**
