### PR TITLE
New Sage color

### PR DESCRIPTION
**Pull request by philschanely**
## Description

This PR updates the set of colors assigned to the Sage color palette per Design specification. See [Sage Design (WIP)](https://www.figma.com/file/xlUFoRTjsFePavVT85SmLL/Sage-Design-WIP?node-id=7932%3A246)

- [x] Update colors
- [x] Update icon
- [x] Update colors in graphics
- [x] Update favicon

### Screenshots

Screen Shot 2021-01-26 at 4 04 06 PM

## Test notes

See Design > Colors and other components such as Icon Card, Alert, and Label.

- (Low) Changed value of Sage (Green) colors in system. These new values will be observable in places such where a quick check should ensure these aspects are readable and appear correctly:
   - [ ] "Published" state of status dropdowns in Product outline
   - [ ] "Connected/Success" state of custom domain items in Settings > Domain

### CODE REVIEW

**Review by monkeypox8 — COMMENTED** [review]
Does the change in values for the default Sage green mean that the logo/favicon should be updated as well?

**Comment by philschanely** [comment]
> Does the change in values for the default Sage green mean that the logo/favicon should be updated as well?

I did add the new logo but good point about the favicon.

**Comment by monkeypox8** [comment]
> > Does the change in values for the default Sage green mean that the logo/favicon should be updated as well?
> 
> @monkeypox8 I did add the new logo but good point about the favicon.

Oh! Totally missed that in the file list 👍🏼

**Review by monkeypox8 — APPROVED** [review]
👍🏼 LGTM

**Review by joedakroub — APPROVED** [review]
This color change is really nice; greatly improved to my eyes. 👍🏼

**Pull request merged**
