### PR TITLE
Card row alignment schema

### PR DESCRIPTION
**Pull request by philschanely**
## Description

This PR udpates the schema settings for CardRow vertical_align to match those for PanelRow.

## Testing in `sage-lib`

Observe no impact on Card component rendering.

Screen Shot 2021-08-23 at 3 51 51 PM

## Testing in `kajabi-products`

1. (LOW) Internal updates to schema for CardRow component. No impact on usages expected.

## Related

#712 

Side effect: Icon alignment issue is apparent. #742 filed.

### CODE REVIEW

**Review by pixelflips — APPROVED** [review]
LGTM! 👍🏼

**Review by anechol — APPROVED** [review]
🚀

**Review by monkeypox8 — APPROVED** [review]
👍🏼 LGTM! Could we also document this setting in the card properties?

**Comment by philschanely** [comment]
@monkeypox8 Yes! however it seems that all the subcomponents of Panel and Card could perhaps be broken out into separate pages in order to be documented them better and improve the `panel` and `card` pages as they stand... Not sure how to do just this one piece here without a full improvement. I'll file tickets for those and should have time to get to them this sprint.

**Pull request merged**
