### PR TITLE
Panel and Card footer alignment

### PR DESCRIPTION
**Pull request by monkeypox8**
## Description
On small screen devices, the `SagePanelFooter` component sets `justify-content: end` rather than `justify-content: flex-end` as expected on the flex container parent, causing the button alignment to be left-justified. This doesn't appear to be intended, as justifying the buttons to the right edge seems to be the pattern for all existing layouts in Figma.

Update: We've confirmed with the design team that the right-justified layout is correct.

At larger screen sizes, the container is set to `display: grid`, so it should not be affected. **Still, the potential for a breaking change exists, so we'll need to thoroughly test existing uses of `SagePanelFooter`, which are listed below.**

#### Panel
|  before  |  after  |
|--------|--------|
|panel_footer-before|panel_footer-after|

#### Card
|  before  |  after  |
|--------|--------|
|card_footer-before|card_footer-after|

## Test notes
**this may potentially cause layouts to shift**
Known areas in use:
- [x] Coupons admin `app/views/admin/coupons/_form.html.erb`
- [ ] Account verifications admin:
  - `app/views/admin/account_verifications/verify_error.html.erb`
  - `app/views/admin/account_verifications/verify.html.erb`
- [x] Email Sending Domains:
  - `app/views/admin/email_sending_domains/_error.html.erb`
  - `app/views/admin/email_sending_domains/_form.html.erb`
  - `app/views/admin/email_sending_domains/_pending_dns_confirmation.html.erb`
  - `app/views/admin/email_sending_domains/_pending_dns.html.erb`
  - `app/views/admin/email_sending_domains/_retrying.html.erb`
  - `app/views/admin/email_sending_domains/_timeout.html.erb`
  - `app/views/admin/email_sending_domains/_verified.html.erb`
- [ ] Landing pages add website modal `app/views/admin/landing_pages/_add_website_page_modal.html.erb`
- [ ] Navbar admin: `app/views/admin/navbars/_navbar.html.erb`
- [x] Offer admin:
  - `app/views/admin/offers/v3/_price_panel.html.erb`
- [ ] Access upgrade breakdown: `app/views/admin/shared/_access_upgrade_breakdown.html.erb`
- [x] Custom domains:
  - `app/views/admin/site_custom_domains_v2/cname_help.html.erb` 
  - `app/views/admin/site_custom_domains_v2/nameservers_help.html.erb`
  - `app/views/admin/site_custom_domains_v2/new.html.erb`
- [ ] Upgrade null view: `app/views/shared/_upgrade_null_view.erb`

### CODE REVIEW

**Review by joedakroub — APPROVED** [review]
Works perfectly. Thanks Kevin! 👍🏼

**Review by pixelflips — APPROVED** [review]
🔥  LGTM!

**Review by QuintonJason — APPROVED** [review]

**Review by philschanely — APPROVED** [review]
Checked in Manage domain (custom domain)

**Comment by pixelflips** [comment]
@monkeypox8 Double checked Email Sending Domains. No issues found.

**Pull request merged**
