### PR TITLE
[SAGE-759] expandable card active

### LINKED ISSUE #759: [Improvement] Include an option for `expanded` in Expandable Card component
## Description

Currently, the expandable card component defaults to a closed or inactive state. It would be helpful to have an option to load the component in an active state where the card is expanded rather closed.

## Design
[Figma](https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/%5BWIP%5D-Sage-3-%E2%80%94-Admin-Components?node-id=6999%3A23010)
[Sage docs](http://sage-design-system.kajabi.com/pages/component/expandable_card)

## Additional Information
[Slack thread for additional context](https://kajabi.slack.com/archives/C02ASAATRQA/p1630505577002200)

### PR DESCRIPTION
**Pull request by monicawheeler**
Resolves #759 

## Description

Provides an option for the expandable card component to allow for devs to load the expandable card expanded, rather than closed.

## Screenshots

|  Before  |  After  |
|--------|--------|
|Screen Shot 2021-09-16 at 2 30 54 PM |Screen Shot 2021-09-16 at 2 15 45 PM|

## Testing in `sage-lib`

1. Navigate to the [Expandable Card component](http://localhost:4000/pages/component/expandable_card)
2. Note that the first card is loaded "expanded" or "open"
3. Confirm the card closes and reopens
4. Confirm that the other cards open and close

## Testing in `kajabi-products`

1. (**MEDIUM**) Expanded card update is a new option within the expandable cards and instances of expandable cards should be verified to confirm no regressions, for example:
    -  [ ] Fowarding Page Rule: Step 5 in Settings -> Domain -> Cloudflare account setup under "Setup Forwarding Page Rules"

### CODE REVIEW

**Review by AndrwM — COMMENTED** [review]
LGTM! This has the functionality we need to complete the cycle.

**Comment by AndrwM** [comment]
Just to make sure its on the radar but not breaking for our cycle is the option to have the visual treatment as: https://www.figma.com/file/zTHwmRx2GpM1Omq2HYbfdb/Coaching-%2F-Create-%26-Manage?node-id=5924%3A48961

**Comment by monicawheeler** [comment]
@AndrwM - FYI, I have an issue for this: https://github.com/Kajabi/sage-lib/issues/802

**Review by anechol — APPROVED** [review]
LGTM!! 🚀

**Pull request merged**
