### PR TITLE
Feature Toggle - update toggle to allow for more flexibility

### PR DESCRIPTION
**Pull request by QuintonJason**
## Description

* remove hardcoded switch to allow for flexible component usage

### Steps for testing
1. Verify the implementation to now use raw html instead of a predefined child switch component

### CODE REVIEW

**Review by philschanely — APPROVED** [review]
No concerns here. Nice updates! :thumbs

**Review by monkeypox8 — COMMENTED** [review]
The switch is outputting twice on the second example for me. Almost as if the `content_for` on the first example is picked up again:

feature-toggle

**Comment by QuintonJason** [comment]
> I'm seeing some odd behavior on my local. The switch is outputting twice on the second example. Almost as if the `content_for` on the first example is picked up again:
> 
> feature-toggle

@monkeypox8 used a different approach to resolve.

**Review by monkeypox8 — APPROVED** [review]
👍🏼 Looks great!

**Pull request merged**
